name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Installs CMake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: '3.14.4'
    - name: Uninstall CMake 3.18
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --uninstall "cmake;3.18.1" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
