name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Caches build intermediates
      uses: actions/cache@v2
      with:
        path: |
          **/build/generated
          **/build/intermediates
          **/build/outputs
          distribution
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Installs CMake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: '3.14.4'
    - name: Build with Gradle
      run: ./gradlew assembleMarathon2Release
